[package]
name = "oot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oot-sys = { path = "oot-sys" }

[workspace]
members = [
    "oot-sys"
]
