[package]
name = "oot-sys"
version = "0.1.0"
edition = "2021"
links = "oot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
glob = "0.3"
